package io.titan.modules.core.entity;

import java.io.Serializable;

public class AccountInfo implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_info.id
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_info.address
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_info.public_key
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	private String publicKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column account_info.last_nonce
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	private String lastNonce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table account_info
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_info.id
	 * @return  the value of account_info.id
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_info.id
	 * @param id  the value for account_info.id
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_info.address
	 * @return  the value of account_info.address
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_info.address
	 * @param address  the value for account_info.address
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_info.public_key
	 * @return  the value of account_info.public_key
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	public String getPublicKey() {
		return publicKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_info.public_key
	 * @param publicKey  the value for account_info.public_key
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column account_info.last_nonce
	 * @return  the value of account_info.last_nonce
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	public String getLastNonce() {
		return lastNonce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column account_info.last_nonce
	 * @param lastNonce  the value for account_info.last_nonce
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	public void setLastNonce(String lastNonce) {
		this.lastNonce = lastNonce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table account_info
	 * @mbg.generated  Fri Jun 12 18:30:46 CST 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", address=").append(address);
		sb.append(", publicKey=").append(publicKey);
		sb.append(", lastNonce=").append(lastNonce);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}