package io.titan.modules.core.entity;

import java.io.Serializable;
import java.util.Date;

public class ChainInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_info.head_block_num
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    private Long headBlockNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_info.head_block_hash
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    private String headBlockHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_info.head_block_time
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    private Date headBlockTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_info.head_block_producer
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    private String headBlockProducer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_info.total_qty
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    private Long totalQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chain_info.version
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chain_info
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_info.head_block_num
     *
     * @return the value of chain_info.head_block_num
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public Long getHeadBlockNum() {
        return headBlockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_info.head_block_num
     *
     * @param headBlockNum the value for chain_info.head_block_num
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public void setHeadBlockNum(Long headBlockNum) {
        this.headBlockNum = headBlockNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_info.head_block_hash
     *
     * @return the value of chain_info.head_block_hash
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public String getHeadBlockHash() {
        return headBlockHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_info.head_block_hash
     *
     * @param headBlockHash the value for chain_info.head_block_hash
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public void setHeadBlockHash(String headBlockHash) {
        this.headBlockHash = headBlockHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_info.head_block_time
     *
     * @return the value of chain_info.head_block_time
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public Date getHeadBlockTime() {
        return headBlockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_info.head_block_time
     *
     * @param headBlockTime the value for chain_info.head_block_time
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public void setHeadBlockTime(Date headBlockTime) {
        this.headBlockTime = headBlockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_info.head_block_producer
     *
     * @return the value of chain_info.head_block_producer
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public String getHeadBlockProducer() {
        return headBlockProducer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_info.head_block_producer
     *
     * @param headBlockProducer the value for chain_info.head_block_producer
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public void setHeadBlockProducer(String headBlockProducer) {
        this.headBlockProducer = headBlockProducer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_info.total_qty
     *
     * @return the value of chain_info.total_qty
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public Long getTotalQty() {
        return totalQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_info.total_qty
     *
     * @param totalQty the value for chain_info.total_qty
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public void setTotalQty(Long totalQty) {
        this.totalQty = totalQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chain_info.version
     *
     * @return the value of chain_info.version
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chain_info.version
     *
     * @param version the value for chain_info.version
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chain_info
     *
     * @mbg.generated Sat Jul 25 16:11:11 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", headBlockNum=").append(headBlockNum);
        sb.append(", headBlockHash=").append(headBlockHash);
        sb.append(", headBlockTime=").append(headBlockTime);
        sb.append(", headBlockProducer=").append(headBlockProducer);
        sb.append(", totalQty=").append(totalQty);
        sb.append(", version=").append(version);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}