package io.titan.modules.core.entity;

import java.io.Serializable;
import java.util.Date;

public class TokenInfo implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token_info.id
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token_info.token_name
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	private String tokenName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token_info.token_full_name
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	private String tokenFullName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token_info.contract
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	private String contract;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token_info.precision_number
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	private Integer precisionNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token_info.total_qty
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	private Long totalQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token_info.issue_date
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	private Date issueDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token_info.issue_address
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	private String issueAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column token_info.receive_address
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	private String receiveAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token_info.id
	 * @return  the value of token_info.id
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token_info.id
	 * @param id  the value for token_info.id
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token_info.token_name
	 * @return  the value of token_info.token_name
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public String getTokenName() {
		return tokenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token_info.token_name
	 * @param tokenName  the value for token_info.token_name
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void setTokenName(String tokenName) {
		this.tokenName = tokenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token_info.token_full_name
	 * @return  the value of token_info.token_full_name
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public String getTokenFullName() {
		return tokenFullName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token_info.token_full_name
	 * @param tokenFullName  the value for token_info.token_full_name
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void setTokenFullName(String tokenFullName) {
		this.tokenFullName = tokenFullName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token_info.contract
	 * @return  the value of token_info.contract
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public String getContract() {
		return contract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token_info.contract
	 * @param contract  the value for token_info.contract
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void setContract(String contract) {
		this.contract = contract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token_info.precision_number
	 * @return  the value of token_info.precision_number
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public Integer getPrecisionNumber() {
		return precisionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token_info.precision_number
	 * @param precisionNumber  the value for token_info.precision_number
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void setPrecisionNumber(Integer precisionNumber) {
		this.precisionNumber = precisionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token_info.total_qty
	 * @return  the value of token_info.total_qty
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public Long getTotalQty() {
		return totalQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token_info.total_qty
	 * @param totalQty  the value for token_info.total_qty
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void setTotalQty(Long totalQty) {
		this.totalQty = totalQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token_info.issue_date
	 * @return  the value of token_info.issue_date
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public Date getIssueDate() {
		return issueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token_info.issue_date
	 * @param issueDate  the value for token_info.issue_date
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token_info.issue_address
	 * @return  the value of token_info.issue_address
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public String getIssueAddress() {
		return issueAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token_info.issue_address
	 * @param issueAddress  the value for token_info.issue_address
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void setIssueAddress(String issueAddress) {
		this.issueAddress = issueAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column token_info.receive_address
	 * @return  the value of token_info.receive_address
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public String getReceiveAddress() {
		return receiveAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column token_info.receive_address
	 * @param receiveAddress  the value for token_info.receive_address
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void setReceiveAddress(String receiveAddress) {
		this.receiveAddress = receiveAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", tokenName=").append(tokenName);
		sb.append(", tokenFullName=").append(tokenFullName);
		sb.append(", contract=").append(contract);
		sb.append(", precisionNumber=").append(precisionNumber);
		sb.append(", totalQty=").append(totalQty);
		sb.append(", issueDate=").append(issueDate);
		sb.append(", issueAddress=").append(issueAddress);
		sb.append(", receiveAddress=").append(receiveAddress);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}