package io.titan.modules.core.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TokenInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public TokenInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTokenNameIsNull() {
			addCriterion("token_name is null");
			return (Criteria) this;
		}

		public Criteria andTokenNameIsNotNull() {
			addCriterion("token_name is not null");
			return (Criteria) this;
		}

		public Criteria andTokenNameEqualTo(String value) {
			addCriterion("token_name =", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameNotEqualTo(String value) {
			addCriterion("token_name <>", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameGreaterThan(String value) {
			addCriterion("token_name >", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameGreaterThanOrEqualTo(String value) {
			addCriterion("token_name >=", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameLessThan(String value) {
			addCriterion("token_name <", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameLessThanOrEqualTo(String value) {
			addCriterion("token_name <=", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameLike(String value) {
			addCriterion("token_name like", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameNotLike(String value) {
			addCriterion("token_name not like", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameIn(List<String> values) {
			addCriterion("token_name in", values, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameNotIn(List<String> values) {
			addCriterion("token_name not in", values, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameBetween(String value1, String value2) {
			addCriterion("token_name between", value1, value2, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameNotBetween(String value1, String value2) {
			addCriterion("token_name not between", value1, value2, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameIsNull() {
			addCriterion("token_full_name is null");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameIsNotNull() {
			addCriterion("token_full_name is not null");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameEqualTo(String value) {
			addCriterion("token_full_name =", value, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameNotEqualTo(String value) {
			addCriterion("token_full_name <>", value, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameGreaterThan(String value) {
			addCriterion("token_full_name >", value, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameGreaterThanOrEqualTo(String value) {
			addCriterion("token_full_name >=", value, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameLessThan(String value) {
			addCriterion("token_full_name <", value, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameLessThanOrEqualTo(String value) {
			addCriterion("token_full_name <=", value, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameLike(String value) {
			addCriterion("token_full_name like", value, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameNotLike(String value) {
			addCriterion("token_full_name not like", value, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameIn(List<String> values) {
			addCriterion("token_full_name in", values, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameNotIn(List<String> values) {
			addCriterion("token_full_name not in", values, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameBetween(String value1, String value2) {
			addCriterion("token_full_name between", value1, value2, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andTokenFullNameNotBetween(String value1, String value2) {
			addCriterion("token_full_name not between", value1, value2, "tokenFullName");
			return (Criteria) this;
		}

		public Criteria andContractIsNull() {
			addCriterion("contract is null");
			return (Criteria) this;
		}

		public Criteria andContractIsNotNull() {
			addCriterion("contract is not null");
			return (Criteria) this;
		}

		public Criteria andContractEqualTo(String value) {
			addCriterion("contract =", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractNotEqualTo(String value) {
			addCriterion("contract <>", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractGreaterThan(String value) {
			addCriterion("contract >", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractGreaterThanOrEqualTo(String value) {
			addCriterion("contract >=", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractLessThan(String value) {
			addCriterion("contract <", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractLessThanOrEqualTo(String value) {
			addCriterion("contract <=", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractLike(String value) {
			addCriterion("contract like", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractNotLike(String value) {
			addCriterion("contract not like", value, "contract");
			return (Criteria) this;
		}

		public Criteria andContractIn(List<String> values) {
			addCriterion("contract in", values, "contract");
			return (Criteria) this;
		}

		public Criteria andContractNotIn(List<String> values) {
			addCriterion("contract not in", values, "contract");
			return (Criteria) this;
		}

		public Criteria andContractBetween(String value1, String value2) {
			addCriterion("contract between", value1, value2, "contract");
			return (Criteria) this;
		}

		public Criteria andContractNotBetween(String value1, String value2) {
			addCriterion("contract not between", value1, value2, "contract");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberIsNull() {
			addCriterion("precision_number is null");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberIsNotNull() {
			addCriterion("precision_number is not null");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberEqualTo(Integer value) {
			addCriterion("precision_number =", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberNotEqualTo(Integer value) {
			addCriterion("precision_number <>", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberGreaterThan(Integer value) {
			addCriterion("precision_number >", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("precision_number >=", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberLessThan(Integer value) {
			addCriterion("precision_number <", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberLessThanOrEqualTo(Integer value) {
			addCriterion("precision_number <=", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberIn(List<Integer> values) {
			addCriterion("precision_number in", values, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberNotIn(List<Integer> values) {
			addCriterion("precision_number not in", values, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberBetween(Integer value1, Integer value2) {
			addCriterion("precision_number between", value1, value2, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("precision_number not between", value1, value2, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andTotalQtyIsNull() {
			addCriterion("total_qty is null");
			return (Criteria) this;
		}

		public Criteria andTotalQtyIsNotNull() {
			addCriterion("total_qty is not null");
			return (Criteria) this;
		}

		public Criteria andTotalQtyEqualTo(Long value) {
			addCriterion("total_qty =", value, "totalQty");
			return (Criteria) this;
		}

		public Criteria andTotalQtyNotEqualTo(Long value) {
			addCriterion("total_qty <>", value, "totalQty");
			return (Criteria) this;
		}

		public Criteria andTotalQtyGreaterThan(Long value) {
			addCriterion("total_qty >", value, "totalQty");
			return (Criteria) this;
		}

		public Criteria andTotalQtyGreaterThanOrEqualTo(Long value) {
			addCriterion("total_qty >=", value, "totalQty");
			return (Criteria) this;
		}

		public Criteria andTotalQtyLessThan(Long value) {
			addCriterion("total_qty <", value, "totalQty");
			return (Criteria) this;
		}

		public Criteria andTotalQtyLessThanOrEqualTo(Long value) {
			addCriterion("total_qty <=", value, "totalQty");
			return (Criteria) this;
		}

		public Criteria andTotalQtyIn(List<Long> values) {
			addCriterion("total_qty in", values, "totalQty");
			return (Criteria) this;
		}

		public Criteria andTotalQtyNotIn(List<Long> values) {
			addCriterion("total_qty not in", values, "totalQty");
			return (Criteria) this;
		}

		public Criteria andTotalQtyBetween(Long value1, Long value2) {
			addCriterion("total_qty between", value1, value2, "totalQty");
			return (Criteria) this;
		}

		public Criteria andTotalQtyNotBetween(Long value1, Long value2) {
			addCriterion("total_qty not between", value1, value2, "totalQty");
			return (Criteria) this;
		}

		public Criteria andIssueDateIsNull() {
			addCriterion("issue_date is null");
			return (Criteria) this;
		}

		public Criteria andIssueDateIsNotNull() {
			addCriterion("issue_date is not null");
			return (Criteria) this;
		}

		public Criteria andIssueDateEqualTo(Date value) {
			addCriterion("issue_date =", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateNotEqualTo(Date value) {
			addCriterion("issue_date <>", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateGreaterThan(Date value) {
			addCriterion("issue_date >", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateGreaterThanOrEqualTo(Date value) {
			addCriterion("issue_date >=", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateLessThan(Date value) {
			addCriterion("issue_date <", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateLessThanOrEqualTo(Date value) {
			addCriterion("issue_date <=", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateIn(List<Date> values) {
			addCriterion("issue_date in", values, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateNotIn(List<Date> values) {
			addCriterion("issue_date not in", values, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateBetween(Date value1, Date value2) {
			addCriterion("issue_date between", value1, value2, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateNotBetween(Date value1, Date value2) {
			addCriterion("issue_date not between", value1, value2, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueAddressIsNull() {
			addCriterion("issue_address is null");
			return (Criteria) this;
		}

		public Criteria andIssueAddressIsNotNull() {
			addCriterion("issue_address is not null");
			return (Criteria) this;
		}

		public Criteria andIssueAddressEqualTo(String value) {
			addCriterion("issue_address =", value, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andIssueAddressNotEqualTo(String value) {
			addCriterion("issue_address <>", value, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andIssueAddressGreaterThan(String value) {
			addCriterion("issue_address >", value, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andIssueAddressGreaterThanOrEqualTo(String value) {
			addCriterion("issue_address >=", value, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andIssueAddressLessThan(String value) {
			addCriterion("issue_address <", value, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andIssueAddressLessThanOrEqualTo(String value) {
			addCriterion("issue_address <=", value, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andIssueAddressLike(String value) {
			addCriterion("issue_address like", value, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andIssueAddressNotLike(String value) {
			addCriterion("issue_address not like", value, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andIssueAddressIn(List<String> values) {
			addCriterion("issue_address in", values, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andIssueAddressNotIn(List<String> values) {
			addCriterion("issue_address not in", values, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andIssueAddressBetween(String value1, String value2) {
			addCriterion("issue_address between", value1, value2, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andIssueAddressNotBetween(String value1, String value2) {
			addCriterion("issue_address not between", value1, value2, "issueAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressIsNull() {
			addCriterion("receive_address is null");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressIsNotNull() {
			addCriterion("receive_address is not null");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressEqualTo(String value) {
			addCriterion("receive_address =", value, "receiveAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressNotEqualTo(String value) {
			addCriterion("receive_address <>", value, "receiveAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressGreaterThan(String value) {
			addCriterion("receive_address >", value, "receiveAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressGreaterThanOrEqualTo(String value) {
			addCriterion("receive_address >=", value, "receiveAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressLessThan(String value) {
			addCriterion("receive_address <", value, "receiveAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressLessThanOrEqualTo(String value) {
			addCriterion("receive_address <=", value, "receiveAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressLike(String value) {
			addCriterion("receive_address like", value, "receiveAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressNotLike(String value) {
			addCriterion("receive_address not like", value, "receiveAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressIn(List<String> values) {
			addCriterion("receive_address in", values, "receiveAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressNotIn(List<String> values) {
			addCriterion("receive_address not in", values, "receiveAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressBetween(String value1, String value2) {
			addCriterion("receive_address between", value1, value2, "receiveAddress");
			return (Criteria) this;
		}

		public Criteria andReceiveAddressNotBetween(String value1, String value2) {
			addCriterion("receive_address not between", value1, value2, "receiveAddress");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table token_info
	 * @mbg.generated  Fri Aug 21 16:30:34 CST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table token_info
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 10 16:31:29 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}